### ISSUE TITLE
Spark Streaming - Error retrieving _changes feed for a database: HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by ThomTel** [cloudant-labs/spark-cloudant#76]
Hi, 

i try to read from a cloudant database via Spark Streaming but get follwing error: 

WARN ReceiverTracker: Error reported by receiver for stream 0: Error retrieving _changes feed for a database xyz: HTTP/1.1 403 Forbidden 
- java.lang.RuntimeException: Error retrieving _changes feed for a database xyz: HTTP/1.1 403 Forbidden
	at com.cloudant.spark.CloudantReceiver$$anonfun$com$cloudant$spark$CloudantReceiver$$receive$1.apply(CloudantReceiver.scala:61)
	at com.cloudant.spark.CloudantReceiver$$anonfun$com$cloudant$spark$CloudantReceiver$$receive$1.apply(CloudantReceiver.scala:48)
	at scalaj.http.HttpRequest$$anonfun$toResponse$3.apply(Http.scala:388)
	at scalaj.http.HttpRequest$$anonfun$toResponse$3.apply(Http.scala:380)
	at scala.Option.getOrElse(Option.scala:121)
	at scalaj.http.HttpRequest.toResponse(Http.scala:380)
	at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:360)
	at scalaj.http.HttpRequest.exec(Http.scala:335)
	at com.cloudant.spark.CloudantReceiver.com$cloudant$spark$CloudantReceiver$$receive(CloudantReceiver.scala:48)
	at com.cloudant.spark.CloudantReceiver$$anon$1.run(CloudantReceiver.scala:20)

Any Idea ? I can open the _changes feed in my browser with the same credentials. 

Thanks in advance !

Thomas

**Comment by mayya-sharipova** [comment]
@ThomTel The error means that the access is forbidden, which means the credentials are wrong. Did you enter valid credentials as in an example here:
https://github.com/cloudant-labs/spark-cloudant/blob/master/cloudant-spark-sql/src/main/scala/com/cloudant/spark/CloudantReceiver.scala#L48

**Comment by ThomTel** [comment]
@mayya-sharipova yes i used valid credentials i just changed the users permissions to admin now i get HTTP/1.1 405 Method Not Allowed

**Comment by mayya-sharipova** [comment]
@ThomTel You can see how a post request is being made here: https://github.com/cloudant-labs/spark-cloudant/blob/master/cloudant-spark-sql/src/main/scala/com/cloudant/spark/CloudantReceiver.scala#L32-L45

Try to make a similar post request with all your credentials, and see if it works. url here is : `protocol + "://"+ host+"/"+dbName+ /_changes?include_docs=true&feed=continuous&heartbeat=3000`.   Default protocol is `https`.

**Comment by ThomTel** [comment]
@mayya-sharipova this request works fine in my browser

**Comment by mayya-sharipova** [comment]
Which connector release are you using: 1.6.4 or 2.0.0? I am going to double-check, running an example myself.

**Comment by ThomTel** [comment]
I tried both - same result .. I would prefer 2.0.0

**Comment by mayya-sharipova** [comment]
@ThomTel  just confirmed that everything works fine with  Spark Streaming using the connector version: https://github.com/cloudant-labs/spark-cloudant/releases/download/v2.0.0/cloudant-spark-v2.0.0-185.jar (below you can see the output).  The last thing I can suggest is to make sure that  your cloudant.protocol is set up as http/https as intended, and since the code is open-sourced, you can debug the url and request objects yourself.



========= 1476131370000 ms =========
Use connectorVersion=2.0.0, dbName=sales, jsonstore.rdd.requestTimeout=900000
========= 1476131380000 ms =========
+--------------------+--------------------+-------+-----+----+
|                 _id|                _rev| amount|month| rep|
+--------------------+--------------------+-------+-----+----+
|c46a10a6131748ab5...|1-8c4d9a17862f609...|2307685|  May|John|
|f7dfdef2d79f8f32a...|1-39db6e13b7a4649...|7552704|  May|John|

**Comment by ThomTel** [comment]
@mayya-sharipova Ok i will try it again. Thanks for your help !
